### Crear un servicio de Corte de Pelo
POST http://localhost:8080/api/servicios
Content-Type: application/json

{
  "nombre": "Peinado fallera simple",
  "descripcion": "Peinado con partidura al medio y 2 tocados a los costados.",
  "precio": 25.00,
  "duracion": 20
}

### Crear un usuario
POST http://localhost:8080/api/usuarios
Content-Type: application/json

{
  "nombre": "Montse Segovia",
  "email": "segoviamontse2015@gmail.com",
  "telefono": "+34689689123",
  "password": "password123",
  "fecha_registro": "2026-03-17"
}

### Agendar una Cita
POST http://localhost:8080/api/citas
Content-Type: application/json

{
  "usuario": {
    "id_usuario": 3
  },
  "servicio": {
    "id_servicio": 4
  },
  "fecha_hora": "2026-03-19T07:30:00"
}

### Obtener lista de usuarios

GET http://localhost:8080/api/usuarios