spring.application.name=peluqueria

#puerto del backend
server.port=8080

#conexión a postgresql
spring.datasource.url=jdbc:postgresql://localhost:5432/peluqueria_db
spring.datasource.username=postgres
spring.datasource.password=12345678

#configuración de JPA/hibernate
#update: actualiza la base de datos según los cambios en las entidades automáticamente
spring.jpa.hibernate.ddl-auto=update

#imprime el código SQL generado por Hibernate en la consola
spring.jpa.show-sql=true