spring.application.name=peluqueria

#puerto del backend
server.port=8080

#conexion a postgresql
spring.datasource.url=jdbc:postgresql://localhost:5432/peluqueria_db
spring.datasource.username=postgres
spring.datasource.password=12345678

#configuracion de JPA/hibernate
#update: actualiza la base de datos segun los cambios en las entidades automaticamente
spring.jpa.hibernate.ddl-auto=update

#imprime el codigo SQL generado por Hibernate en la consola
spring.jpa.show-sql=true
