# Perfil de produccion

# Hibernate solo valida que las tablas coincidan con las entidades, no modifica la BD
spring.jpa.hibernate.ddl-auto=validate

# No imprimir queries SQL en consola
spring.jpa.show-sql=false
