-- V11: Galeria de trabajos de la peluqueria. Varias fotos, con orden manual.
-- Como en el resto del proyecto se guarda la CLAVE del objeto en el almacen, no
-- la URL: la URL se monta al leer (ver GaleriaService), asi que cambiar de bucket
-- o de proveedor no obliga a migrar ninguna fila.
-- La miniatura es una clave aparte porque la rejilla se sirve solo con ella: el
-- limite del plan gratuito de Storage es el trafico, no el espacio, y pintar la
-- imagen grande en una rejilla de 20 fotos lo multiplica por diez.
CREATE TABLE galeria_fotos (
    id_foto         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    imagen_clave    VARCHAR(255) NOT NULL,
    miniatura_clave VARCHAR(255),
    titulo          VARCHAR(120),
    orden           INTEGER      NOT NULL DEFAULT 0,
    fecha_subida    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_galeria_orden ON galeria_fotos (orden, id_foto);
