-- V12: El rol PELUQUERO y lo que necesita para existir.
--
-- 1) Vinculo peluquero <-> cuenta. La tabla peluqueros era una ficha suelta (nombre y
--    activo) sin ninguna relacion con usuarios, asi que un peluquero no podia entrar a
--    ningun sitio. El usuario_id es NULLABLE y UNIQUE a proposito: nullable porque las
--    fichas que ya existen no tienen cuenta y se siguen pudiendo crear asi (el admin
--    agenda por ellos), y unique porque una cuenta no puede ser dos peluqueros.
--
-- 2) Comision. El porcentaje vive en la ficha del peluquero, con excepciones por
--    servicio en comisiones_servicio (un tinte no comisiona como un corte).
--
-- 3) Cierre de la cita. precio_aplicado y comision_porcentaje_aplicado se congelan al
--    completar: si no, subir el precio de un servicio cambiaria la produccion y la
--    comision YA LIQUIDADAS de meses anteriores. Son NULL mientras la cita no se cierra.
ALTER TABLE peluqueros ADD COLUMN usuario_id INTEGER UNIQUE REFERENCES usuarios (id_usuario);
ALTER TABLE peluqueros ADD COLUMN comision_porcentaje NUMERIC(5, 2) NOT NULL DEFAULT 0;

CREATE TABLE comisiones_servicio (
    id_comision  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    peluquero_id INTEGER      NOT NULL REFERENCES peluqueros (id_peluquero) ON DELETE CASCADE,
    servicio_id  INTEGER      NOT NULL REFERENCES servicios (id_servicio) ON DELETE CASCADE,
    porcentaje   NUMERIC(5, 2) NOT NULL,
    CONSTRAINT uk_comision_peluquero_servicio UNIQUE (peluquero_id, servicio_id)
);

ALTER TABLE citas ADD COLUMN precio_aplicado NUMERIC(10, 2);
ALTER TABLE citas ADD COLUMN comision_porcentaje_aplicado NUMERIC(5, 2);
ALTER TABLE citas ADD COLUMN fecha_cierre TIMESTAMP;
-- Que paso, en palabras del que cerro la cita. Es el campo que pidio el negocio para
-- anular sin obligar al cliente a confirmar nada.
ALTER TABLE citas ADD COLUMN observaciones TEXT;
-- Si al anular se avisó al cliente por telefono o en persona. El email automatico se
-- manda igual; esto es el registro de que hubo contacto humano.
ALTER TABLE citas ADD COLUMN cliente_contactado BOOLEAN NOT NULL DEFAULT FALSE;
-- Quien dejo la cita en su estado final (completada, no asistio o anulada).
ALTER TABLE citas ADD COLUMN cerrada_por INTEGER REFERENCES usuarios (id_usuario);

-- La produccion consulta por peluquero + estado + fecha. El indice de peluquero_id que
-- creo la V7 no cubre el estado, que es lo que mas filas descarta.
CREATE INDEX idx_citas_peluquero_estado_fecha ON citas (peluquero_id, estado, fecha_hora);
