-- V1: Esquema base (usuarios, servicios, citas).
-- Equivalente al schema que generaba ddl-auto hasta 2026-06-14, ahora versionado con Flyway.

CREATE TABLE usuarios (
    id_usuario     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre         VARCHAR(50)  NOT NULL,
    email          VARCHAR(100) NOT NULL UNIQUE,
    telefono       VARCHAR(15),
    password       VARCHAR(255) NOT NULL,
    fecha_registro DATE,
    rol            VARCHAR(10)  NOT NULL,
    activo         BOOLEAN      NOT NULL,
    token_version  INTEGER      NOT NULL
);

CREATE TABLE servicios (
    id_servicio INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre      VARCHAR(255)  NOT NULL,
    descripcion TEXT,
    precio      NUMERIC(10, 2),
    duracion    INTEGER,
    activo      BOOLEAN       NOT NULL DEFAULT TRUE
);

CREATE TABLE citas (
    id_cita     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id  INTEGER     NOT NULL REFERENCES usuarios (id_usuario),
    servicio_id INTEGER     NOT NULL REFERENCES servicios (id_servicio),
    fecha_hora  TIMESTAMP   NOT NULL,
    estado      VARCHAR(50)
);
