-- V2: Tokens de recuperacion de contrasena.
-- Guardamos el HASH (SHA-256 hex) del token, nunca el token en claro: si se filtra la
-- tabla, los hashes no sirven para restablecer. Cada token es de un solo uso y caduca.

CREATE TABLE password_reset_token (
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token_hash VARCHAR(64) NOT NULL UNIQUE,
    usuario_id INTEGER     NOT NULL REFERENCES usuarios (id_usuario),
    expira_en  TIMESTAMP   NOT NULL,
    usado      BOOLEAN     NOT NULL DEFAULT FALSE,
    creado_en  TIMESTAMP   NOT NULL
);

CREATE INDEX idx_password_reset_token_hash ON password_reset_token (token_hash);
