-- Refresh tokens (rotacion + deteccion de reuso): almacena el hash SHA-256 del token.
-- familia = cadena de rotaciones nacida de un login; al detectar reuso se revoca la familia entera.
-- token_version = version del usuario al emitir; si cambia (password/rol) el refresh deja de valer.
CREATE TABLE refresh_token (
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token_hash    VARCHAR(64) NOT NULL UNIQUE,
    usuario_id    INTEGER     NOT NULL REFERENCES usuarios (id_usuario),
    familia       VARCHAR(36) NOT NULL,
    token_version INTEGER     NOT NULL,
    expira_en     TIMESTAMP   NOT NULL,
    revocado      BOOLEAN     NOT NULL DEFAULT FALSE,
    creado_en     TIMESTAMP   NOT NULL
);

CREATE INDEX idx_refresh_token_hash ON refresh_token (token_hash);
CREATE INDEX idx_refresh_token_familia ON refresh_token (familia);
