CREATE TABLE pagos (
    id_pago           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cita_id           INTEGER     NOT NULL UNIQUE REFERENCES citas (id_cita),
    monto             NUMERIC(10, 2) NOT NULL,
    metodo_pago       VARCHAR(20) NOT NULL,
    estado_pago       VARCHAR(20) NOT NULL DEFAULT 'PENDIENTE',
    referencia_externa VARCHAR(255),
    fecha_creacion    TIMESTAMP   NOT NULL,
    fecha_pago        TIMESTAMP
);

CREATE INDEX idx_pagos_cita_id ON pagos (cita_id);
CREATE INDEX idx_pagos_referencia_externa ON pagos (referencia_externa);
