-- V7: Multi-peluquero. Tabla de profesionales + FK en citas (nullable para compatibilidad).
CREATE TABLE peluqueros (
    id_peluquero INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre       VARCHAR(100) NOT NULL,
    activo       BOOLEAN      NOT NULL DEFAULT TRUE
);

ALTER TABLE citas ADD COLUMN peluquero_id INTEGER REFERENCES peluqueros (id_peluquero);
CREATE INDEX idx_citas_peluquero_id ON citas (peluquero_id);
