-- V8: Dias en los que la peluqueria no abre (festivos, cierres puntuales).
-- Los dias de la semana cerrados de forma fija (domingo) NO se guardan aqui: se
-- configuran en peluqueria.horario.dias-cerrados.
CREATE TABLE dias_bloqueados (
    id_dia_bloqueado INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha            DATE         NOT NULL UNIQUE,
    motivo           VARCHAR(200)
);

CREATE INDEX idx_dias_bloqueados_fecha ON dias_bloqueados (fecha);
